export const authConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  CODE_REQUEST: "CODE_REQUEST",
  CODE_SUCCESS: "CODE_SUCCESS",
  CODE_FAILURE: "CODE_FAILURE",
  VERIFY_REQUEST: "VERIFY_REQUEST",
  VERIFY_SUCCESS: "VERIFY_SUCCESS",
  VERIFY_FAILURE: "VERIFY_FAILURE",
  PICTURE_REQUEST: "PICTURE_REQUEST",
  PICTURE_SUCCESS: "PICTURE_SUCCESS",
  PICTURE_FAILURE: "PICTURE_FAILURE",
  PROFILE_UPDATE_REQUEST: "PROFILE_UPDATE_REQUEST",
  PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
  PROFILE_UPDATE_FAILURE: "PROFILE_UPDATE_FAILURE",
  PASS_UPDATE_REQUEST: "PASS_UPDATE_REQUEST",
  PASS_UPDATE_SUCCESS: "PASS_UPDATE_SUCCESS",
  PASS_UPDATE_FAILURE: "PASS_UPDATE_FAILURE",
};

export const cartConstants = {
  CART_GET_REQUEST: "CART_GET_REQUEST",
  CART_GET_SUCCESS: "CART_GET_SUCCESS",
  CART_GET_FAILURE: "CART_GET_FAILURE",
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  REMOVE_CART_REQUEST: "REMOVE_CART_REQUEST",
  REMOVE_CART_SUCCESS: "REMOVE_CART_SUCCESS",
  REMOVE_CART_FAILURE: "REMOVE_CART_FAILURE",
};

export const orderConstant = {
  ORDER_PLACE_REQUEST: "ORDER_PLACE_REQUEST",
  ORDER_PLACE_SUCCESS: "ORDER_PLACE_SUCCESS",
  ORDER_PLACE_FAILURE: "ORDER_PLACE_FAILURE",
  ORDER_GET_REQUEST: "ORDER_GET_REQUEST",
  ORDER_GET_SUCCESS: "ORDER_GET_SUCCESS",
  ORDER_GET_FAILURE: "ORDER_GET_FAILURE",
};

export const ticketConst = {
  TICKET_REQUEST: "TICKET_REQUEST",
  TICKET_SUCCESS: "TICKET_SUCCESS",
  TICKET_FAILURE: "TICKET_FAILURE",
};

export const campaignConst = {
  CAMPAIGN_REQUEST: "CAMPAIGN_REQUEST",
  CAMPAIGN_SUCCESS: "CAMPAIGN_SUCCESS",
  CAMPAIGN_FAILURE: "CAMPAIGN_FAILURE",
};

export const productConst = {
  PRODUCT_REQUEST: "PRODUCT_REQUEST",
  PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
  PRODUCT_FAILURE: "PRODUCT_FAILURE",
};
